name: dazle
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cached_network_image: ^3.2.0
  carousel_slider: ^4.0.0
  cupertino_icons: ^1.0.4
  custom_radio_grouped_button: ^2.1.1
  dio: ^4.0.4
  flutter:
    sdk: flutter
  # flutter_auth_buttons: ^0.10.0
  auth_buttons: ^2.0.4
  flutter_clean_architecture: ^5.0.2
  flutter_facebook_auth: ^4.0.1
  flutter_overlay_loader: ^1.0.3
  flutter_svg: ^1.0.3
  flutter_typeahead: ^4.1.1
  google_sign_in: ^5.2.3
  the_apple_sign_in: ^1.1.1
  http: ^0.13.4
  intl: ^0.17.0
  path_provider: ^2.0.9
  pdf: ^3.7.1
  pin_code_fields: ^7.3.0
  screenshot: ^1.2.3
  share_plus: ^4.0.9
  shared_preferences: ^2.0.13
  wechat_assets_picker: ^7.0.0
  # open_file: ^3.2.1
  permission_handler: ^8.3.0
  dotted_border: ^2.0.0+2
  image_picker: ^0.8.4+8
  printing: ^5.7.2
  intl_phone_number_input: ^0.7.0+2
  pattern_formatter: ^2.0.0
  flutter_image_compress: ^1.1.0
  google_maps_flutter:
  geolocator: ^8.2.0
  flutter_google_places: ^0.3.0
  flutter_switch: ^0.3.2
  shimmer: ^2.0.0
  grouped_list: ^4.2.0
  # file_picker: ^4.5.1
  flutter_easyloading: ^3.0.5
  mixpanel_flutter: ^1.5.1
  fluttertoast: ^8.0.9
  dropdown_search: ^0.5.0
  update_available: ^2.1.0
  upgrader: ^4.4.0
  percent_indicator: ^3.0.1
  month_year_picker: ^0.1.0+3
  # better_open_file: ^3.6.4
  open_filex: ^4.3.0

dependency_overrides:
  google_api_headers: ^1.3.0-dev.0
  device_info_plus_windows: ^6.0.0
  


dev_dependencies:
  device_preview: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
    - assets/icons/tab_bar/
    - fonts/

  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Regular.ttf
