name: dazle
description: A new Flutter project.
version: 1.0.0+1

environment:
    sdk: '>=2.12.0 <3.0.0'

dependencies:
    cached_network_image: ^3.2.0
    carousel_slider: ^4.0.0
    cupertino_icons: ^1.0.4
    custom_radio_grouped_button: ^2.1.1
    dio: ^4.0.4
    flutter:
        sdk: flutter
    # flutter_auth_buttons: ^0.10.0
    auth_buttons: ^2.0.4
    flutter_clean_architecture: ^5.0.2
    flutter_facebook_auth: ^4.0.1
    flutter_overlay_loader: ^1.0.3
    flutter_svg: ^1.0.3
    flutter_typeahead: ^3.2.4
    google_sign_in: ^5.2.3
    http: ^0.13.4
    intl: ^0.17.0
    path_provider: ^2.0.9
    pdf: ^3.7.1
    pin_code_fields: ^7.3.0
    screenshot: ^1.2.3
    share_plus: ^3.0.4
    shared_preferences: ^2.0.13
    wechat_assets_picker: ^6.3.1
    open_file: ^3.2.1
    permission_handler: ^8.3.0
    # downloads_path_provider: ^0.1.0
    dotted_border: ^2.0.0+2
    image_picker: ^0.8.4+8


dev_dependencies:
    device_preview: ^1.0.0
    flutter_test:
        sdk: flutter

flutter:
    uses-material-design: true
    assets:
        - assets/
        - assets/icons/
        - assets/icons/tab_bar/
    fonts:
        - family: Poppins
          fonts:
              - asset: fonts/Poppins-Regular.ttf
